#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Repo-root .env (gitignored). This script lives in .scratch/hosted-canonical-backend/.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

_upsert_gcp_secret() {
  local name="$1" value="$2"
  if ! command -v gcloud >/dev/null 2>&1; then
    SKIPPED+=("GCP secret $name (gcloud missing)")
    warn "gcloud not on PATH; skipped Secret Manager for $name"
    return
  fi
  if gcloud secrets describe "$name" --project=tan-coffee --quiet >/dev/null 2>&1; then
    printf '%s' "$value" | gcloud secrets versions add "$name" --project=tan-coffee --data-file=- --quiet
  else
    printf '%s' "$value" | gcloud secrets create "$name" \
      --project=tan-coffee --replication-policy=automatic --data-file=- --quiet
  fi
  printf '  %s✓ stored%s %s in Secret Manager (project tan-coffee)\n' "$GREEN" "$RESET" "$name"
}

banner "studio.tan.coffee: Vercel DNS + Google OAuth"

write_env GCP_PROJECT_ID tan-coffee
write_env GCP_PROJECT_NUMBER 1033405121253
write_env GCP_REGION us-west1
write_env STUDIO_ORIGIN https://studio.tan.coffee
write_env GOOGLE_OAUTH_REDIRECT_URI https://studio.tan.coffee/auth/google/callback

# ── 1. Delegate studio.tan.coffee to Cloud DNS (apex stays on Vercel) ──
stage "Vercel DNS: delegate studio.tan.coffee"
say "Apex tan.coffee stays on Vercel for the public site."
say "studio.tan.coffee is a Cloud DNS zone so OpenTofu can later write the VM A record."
say "Cloud DNS nameservers:"
note "  ns-cloud-a1.googledomains.com"
note "  ns-cloud-a2.googledomains.com"
note "  ns-cloud-a3.googledomains.com"
note "  ns-cloud-a4.googledomains.com"
open_url "https://vercel.com/xroma/~/domains/tan.coffee"
step "If studio.tan.coffee is assigned to a Vercel project, open that project → Settings → Domains and remove it. Vercel A records for studio must go, or they fight the NS delegation."
step "On tan.coffee → DNS records, delete any A / AAAA / CNAME whose name is studio."
step "Add four NS records, one at a time:"
note "  Name: studio    Type: NS    Value: ns-cloud-a1.googledomains.com"
note "  Name: studio    Type: NS    Value: ns-cloud-a2.googledomains.com"
note "  Name: studio    Type: NS    Value: ns-cloud-a3.googledomains.com"
note "  Name: studio    Type: NS    Value: ns-cloud-a4.googledomains.com"
step "Leave the apex (tan.coffee) A records alone."
pause "Press Enter after the four NS records are saved."
say "Checking Vercel nameservers for the delegation…"
NS_OUT="$(dig NS studio.tan.coffee @ns1.vercel-dns.com +short 2>/dev/null || true)"
if printf '%s\n' "$NS_OUT" | grep -q 'ns-cloud-a1.googledomains.com'; then
  note "Vercel already serves the Cloud DNS NS set for studio.tan.coffee."
else
  warn "dig @ns1.vercel-dns.com does not yet show Cloud DNS NS records."
  note "Got: ${NS_OUT:-<empty>}"
  note "TTL on the old A records was 1800s. Re-run this stage later, or wait and dig NS studio.tan.coffee @ns1.vercel-dns.com"
fi

# ── 2. Google Auth Platform branding + audience ──
stage "Google Auth Platform: branding and audience"
say "Sign in with Google for one operator. Keep the app External + Testing."
say "Do not publish; do not request scopes beyond openid / email / profile."
open_url "https://console.cloud.google.com/auth/overview?project=tan-coffee"
step "If you see Get started, click it. Otherwise open Branding in the left nav."
step "App name: Tan Studio"
step "User support email: operator@example.com (or the Google account you will sign in with)."
step "Developer contact: the same address."
step "Skip the logo. Skip homepage / privacy / terms — those are for a published app."
step "Audience: External. Publishing status: Testing. Do not click Publish app."
pause "Press Enter after branding + audience are saved."

# ── 3. Authorized domain tan.coffee ──
stage "Verify tan.coffee as an authorized domain"
say "Google will not accept https://studio.tan.coffee as an origin or redirect until tan.coffee is a verified authorized domain."
open_url "https://search.google.com/search-console"
step "Add property → Domain → tan.coffee → Continue."
step "Copy the google-site-verification TXT value Google shows."
open_url "https://vercel.com/xroma/~/domains/tan.coffee"
step "Add a TXT record: Name empty (or @), Value the google-site-verification string."
step "Back in Search Console, click Verify."
open_url "https://console.cloud.google.com/auth/branding?project=tan-coffee"
step "Authorized domains → add tan.coffee → Save. studio.tan.coffee is then allowed as a subdomain."
pause "Press Enter after tan.coffee is verified and listed under Authorized domains."

# ── 4. Web OAuth client ──
stage "Create the Web OAuth client"
say "Client secret is shown once. This stage writes it to .env (gitignored) and GCP Secret Manager."
open_url "https://console.cloud.google.com/auth/clients?project=tan-coffee"
step "Create client → Application type: Web application."
step "Name: studio.tan.coffee"
step "Authorized JavaScript origins → Add URI → https://studio.tan.coffee"
step "Authorized redirect URIs → Add URI → https://studio.tan.coffee/auth/google/callback"
step "Create. Copy Client ID (ends with .apps.googleusercontent.com)."
ask GOOGLE_OAUTH_CLIENT_ID "Paste the Client ID:"
step "Copy the Client secret now. After this dialog it is hashed; you cannot read it again."
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the Client secret:"
if [[ -z "${GOOGLE_OAUTH_CLIENT_ID:-}" || -z "${GOOGLE_OAUTH_CLIENT_SECRET:-}" ]]; then
  warn "Client ID or secret was empty. Re-run this stage. If you already closed the secret dialog, rotate: Clients → this client → Add secret."
else
  write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
  write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"
  _upsert_gcp_secret google-oauth-client-id "$GOOGLE_OAUTH_CLIENT_ID"
  _upsert_gcp_secret google-oauth-client-secret "$GOOGLE_OAUTH_CLIENT_SECRET"
fi
open_url "https://console.cloud.google.com/auth/audience?project=tan-coffee"
step "Test users → Add users → operator@example.com (change it in the next stage if the operator email is different)."
pause "Press Enter after the test user is added."

# ── 5. Operator email allowlist ──
stage "Operator Google email"
say "Hosted mode allowlists exactly one email. GCP owner today is operator@example.com."
ask OPERATOR_GOOGLE_EMAIL "Operator Google email (the one that may sign in):"
if [[ -z "${OPERATOR_GOOGLE_EMAIL:-}" ]]; then
  OPERATOR_GOOGLE_EMAIL="operator@example.com"
fi
write_env OPERATOR_GOOGLE_EMAIL "$OPERATOR_GOOGLE_EMAIL"
note "Ticket 03 (hosted OIDC) must use redirect https://studio.tan.coffee/auth/google/callback"

finish
note "Apex tan.coffee was not pointed at GCP. OpenTofu (ticket 04) can now own the studio zone."
note "Budget tan-coffee hosted notebook is \$5/month on billing account <billing account, see console>; mail goes to the billing admin."

