import { describe, expect, test } from "bun:test"

import {
  NativeFormatError,
  parseLosslessNative,
  serializeLosslessNative,
} from "../src"

const encoder = new TextEncoder()
const decoder = new TextDecoder()

describe("lossless native document", () => {
  test("retains BOM, duplicate keys, comments, ordering, and mixed endings", () => {
    const bytes = Uint8Array.from([
      0xef,
      0xbb,
      0xbf,
      ...encoder.encode(
        "name: First\r\n# retained comment\nname:\tSecond\runknown tail"
      ),
    ])
    const document = parseLosslessNative(bytes)

    expect(document.encoding).toBe("utf-8-bom")
    expect(document.lineEnding).toBe("mixed")
    expect(document.nodes.map((node) => node.kind)).toEqual([
      "property",
      "unknown",
      "property",
      "unknown",
    ])
    expect(document.semanticView.properties).toEqual([
      { key: "name", value: "First", nodeIndex: 0 },
      { key: "name", value: "Second", nodeIndex: 2 },
    ])
    expect(document.semanticView.lastValueByKey.name).toBe("Second")
  })

  test("serializes an empty edit set byte-for-byte identically", () => {
    const source = encoder.encode("alpha: 1\r\n\r\nalpha : 2\nraw,value\r")
    const document = parseLosslessNative(source)
    const result = serializeLosslessNative(document, [])

    expect(result.changes).toEqual([])
    expect(result.bytes).not.toBe(document.originalBytes)
    expect(result.bytes).toEqual(source)
  })

  test("preserves every byte outside a supported property value edit", () => {
    const source = encoder.encode("first: 1\r\nsecond:\told\nlast: 3")
    const document = parseLosslessNative(source)
    const result = serializeLosslessNative(document, [
      {
        kind: "replace_property_value",
        nodeIndex: 1,
        value: encoder.encode("new value"),
      },
    ])

    expect(decoder.decode(result.bytes)).toBe(
      "first: 1\r\nsecond:\tnew value\nlast: 3"
    )
    expect(result.changes).toHaveLength(1)
  })

  test("rejects edits that target non-properties or inject records", () => {
    const document = parseLosslessNative(encoder.encode("raw line\nkey: value"))
    expect(() =>
      serializeLosslessNative(document, [
        {
          kind: "replace_property_value",
          nodeIndex: 0,
          value: encoder.encode("no"),
        },
      ])
    ).toThrow(NativeFormatError)
    expect(() =>
      serializeLosslessNative(document, [
        {
          kind: "replace_property_value",
          nodeIndex: 1,
          value: encoder.encode("injected\nrecord"),
        },
      ])
    ).toThrow(NativeFormatError)
  })

  test("round-trips many generated byte layouts with no edits", () => {
    const endings = ["\n", "\r\n", "\r", ""] as const
    let state = 0x5eed1234
    for (let example = 0; example < 300; example += 1) {
      const lines: string[] = []
      const lineCount = 1 + random(12)
      for (let line = 0; line < lineCount; line += 1) {
        const kind = random(4)
        const value =
          kind === 0
            ? `key${random(5)}: value-${random(10_000)}`
            : kind === 1
              ? `# comment ${random(10_000)}`
              : kind === 2
                ? ""
                : `unknown-${random(10_000)}`
        const ending =
          line === lineCount - 1
            ? endings[random(endings.length)]
            : endings[random(endings.length - 1)]
        lines.push(value + ending)
      }
      const source = encoder.encode(lines.join(""))
      const roundTrip = serializeLosslessNative(
        parseLosslessNative(source)
      ).bytes
      expect(roundTrip).toEqual(source)
    }

    function random(maximum: number): number {
      state = (Math.imul(state, 1_103_515_245) + 12_345) >>> 0
      return state % maximum
    }
  })

  test("retains invalid UTF-8 as an opaque, round-trippable document", () => {
    const source = Uint8Array.of(0x6b, 0x3a, 0x20, 0xff, 0x0a)
    const document = parseLosslessNative(source)
    expect(document.encoding).toBe("unknown")
    expect(document.diagnostics).toMatchObject([{ code: "invalid_utf8" }])
    expect(serializeLosslessNative(document).bytes).toEqual(source)
  })
})
